package com.lifetech.dhap.pathcloud.application.domain;

import com.lifetech.dhap.pathcloud.application.application.condition.SampleCondition;
import com.lifetech.dhap.pathcloud.application.domain.model.Sample;

import java.util.List;

public interface SampleRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    int insert(Sample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    Sample selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    List<Sample> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    int updateByPrimaryKey(Sample record);

    Long last();

    List<Sample> selectByPathId(long pathId);

    List<Sample> selectByApplicationId(SampleCondition sampleCondition);
    List<Long> selectIdsByApplicationId(SampleCondition sampleCondition);

    Long countByCondition(SampleCondition sampleCondition);
}