package com.lifetech.dhap.pathcloud.application.domain.model;

import java.io.Serializable;
import java.util.Date;

public class ApplicationIhc implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_ihc.id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_ihc.departments
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Integer departments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_ihc.apply_user
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private String applyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_ihc.apply_tel
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private String applyTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_ihc.create_by
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_ihc.update_by
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_ihc.create_time
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_ihc.update_time
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application_ihc
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_ihc.id
     *
     * @return the value of application_ihc.id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_ihc.id
     *
     * @param id the value for application_ihc.id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_ihc.departments
     *
     * @return the value of application_ihc.departments
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Integer getDepartments() {
        return departments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_ihc.departments
     *
     * @param departments the value for application_ihc.departments
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setDepartments(Integer departments) {
        this.departments = departments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_ihc.apply_user
     *
     * @return the value of application_ihc.apply_user
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public String getApplyUser() {
        return applyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_ihc.apply_user
     *
     * @param applyUser the value for application_ihc.apply_user
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setApplyUser(String applyUser) {
        this.applyUser = applyUser == null ? null : applyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_ihc.apply_tel
     *
     * @return the value of application_ihc.apply_tel
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public String getApplyTel() {
        return applyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_ihc.apply_tel
     *
     * @param applyTel the value for application_ihc.apply_tel
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setApplyTel(String applyTel) {
        this.applyTel = applyTel == null ? null : applyTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_ihc.create_by
     *
     * @return the value of application_ihc.create_by
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_ihc.create_by
     *
     * @param createBy the value for application_ihc.create_by
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_ihc.update_by
     *
     * @return the value of application_ihc.update_by
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_ihc.update_by
     *
     * @param updateBy the value for application_ihc.update_by
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_ihc.create_time
     *
     * @return the value of application_ihc.create_time
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_ihc.create_time
     *
     * @param createTime the value for application_ihc.create_time
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_ihc.update_time
     *
     * @return the value of application_ihc.update_time
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_ihc.update_time
     *
     * @param updateTime the value for application_ihc.update_time
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}