package com.lifetech.dhap.pathcloud.application.domain.model;

import java.io.Serializable;
import java.util.Date;

public class BlockIhc implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.ihc_id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Long ihcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.serial_number
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.path_id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Long pathId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.sub_id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private String subId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.block_id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Long blockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.status
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.special_dye
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Integer specialDye;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.ihc_marker
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private String ihcMarker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.note
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private String note;

    private String result;

    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.create_by
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.update_by
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.create_time
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_ihc.update_time
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    private Date updateTime;

    private String number;

    public Integer getSource() {
        return source;
    }

    public void setSource(Integer source) {
        this.source = source;
    }

    private static final long serialVersionUID = 1L;

    public String getResult() {
        return result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.id
     *
     * @return the value of block_ihc.id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.id
     *
     * @param id the value for block_ihc.id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.ihc_id
     *
     * @return the value of block_ihc.ihc_id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Long getIhcId() {
        return ihcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.ihc_id
     *
     * @param ihcId the value for block_ihc.ihc_id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setIhcId(Long ihcId) {
        this.ihcId = ihcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.serial_number
     *
     * @return the value of block_ihc.serial_number
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.serial_number
     *
     * @param serialNumber the value for block_ihc.serial_number
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.path_id
     *
     * @return the value of block_ihc.path_id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Long getPathId() {
        return pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.path_id
     *
     * @param pathId the value for block_ihc.path_id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setPathId(Long pathId) {
        this.pathId = pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.sub_id
     *
     * @return the value of block_ihc.sub_id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public String getSubId() {
        return subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.sub_id
     *
     * @param subId the value for block_ihc.sub_id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setSubId(String subId) {
        this.subId = subId == null ? null : subId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.block_id
     *
     * @return the value of block_ihc.block_id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Long getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.block_id
     *
     * @param blockId the value for block_ihc.block_id
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setBlockId(Long blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.status
     *
     * @return the value of block_ihc.status
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.status
     *
     * @param status the value for block_ihc.status
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.special_dye
     *
     * @return the value of block_ihc.special_dye
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Integer getSpecialDye() {
        return specialDye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.special_dye
     *
     * @param specialDye the value for block_ihc.special_dye
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setSpecialDye(Integer specialDye) {
        this.specialDye = specialDye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.ihc_marker
     *
     * @return the value of block_ihc.ihc_marker
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public String getIhcMarker() {
        return ihcMarker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.ihc_marker
     *
     * @param ihcMarker the value for block_ihc.ihc_marker
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setIhcMarker(String ihcMarker) {
        this.ihcMarker = ihcMarker == null ? null : ihcMarker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.note
     *
     * @return the value of block_ihc.note
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.note
     *
     * @param note the value for block_ihc.note
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.create_by
     *
     * @return the value of block_ihc.create_by
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.create_by
     *
     * @param createBy the value for block_ihc.create_by
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.update_by
     *
     * @return the value of block_ihc.update_by
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.update_by
     *
     * @param updateBy the value for block_ihc.update_by
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.create_time
     *
     * @return the value of block_ihc.create_time
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.create_time
     *
     * @param createTime the value for block_ihc.create_time
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_ihc.update_time
     *
     * @return the value of block_ihc.update_time
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_ihc.update_time
     *
     * @param updateTime the value for block_ihc.update_time
     *
     * @mbggenerated Fri Mar 31 16:25:57 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}