package com.lifetech.dhap.pathcloud.application.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Sample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.id
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.application_id
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    private Long applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.serial_number
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.name
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.category
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.create_by
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.update_by
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.create_time
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.update_time
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.note
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    private String note;

    private Boolean delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sample
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    private static final long serialVersionUID = 1L;

    public Boolean getDelete() {
        return delete;
    }

    public void setDelete(Boolean delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.id
     *
     * @return the value of sample.id
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.id
     *
     * @param id the value for sample.id
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.application_id
     *
     * @return the value of sample.application_id
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public Long getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.application_id
     *
     * @param applicationId the value for sample.application_id
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public void setApplicationId(Long applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.serial_number
     *
     * @return the value of sample.serial_number
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.serial_number
     *
     * @param serialNumber the value for sample.serial_number
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.name
     *
     * @return the value of sample.name
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.name
     *
     * @param name the value for sample.name
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.category
     *
     * @return the value of sample.category
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.category
     *
     * @param category the value for sample.category
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.create_by
     *
     * @return the value of sample.create_by
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.create_by
     *
     * @param createBy the value for sample.create_by
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.update_by
     *
     * @return the value of sample.update_by
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.update_by
     *
     * @param updateBy the value for sample.update_by
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.create_time
     *
     * @return the value of sample.create_time
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.create_time
     *
     * @param createTime the value for sample.create_time
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.update_time
     *
     * @return the value of sample.update_time
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.update_time
     *
     * @param updateTime the value for sample.update_time
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.note
     *
     * @return the value of sample.note
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.note
     *
     * @param note the value for sample.note
     *
     * @mbggenerated Mon Nov 21 17:13:14 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}