package com.lifetech.dhap.pathcloud.notification.domain;

import com.lifetech.dhap.pathcloud.notification.domain.model.NotificationReceiver;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface NotificationReceiverRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notification_receiver
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    int deleteByPrimaryKey(@Param("notificationId") Long notificationId, @Param("receiverId") String receiverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notification_receiver
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    int insert(NotificationReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notification_receiver
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    NotificationReceiver selectByPrimaryKey(@Param("notificationId") Long notificationId, @Param("receiverId") String receiverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notification_receiver
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    List<NotificationReceiver> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notification_receiver
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    int updateByPrimaryKey(NotificationReceiver record);
}