package com.lifetech.dhap.pathcloud.tracking.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Block implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.id
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.serial_number
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.path_id
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private Long pathId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.sub_id
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private String subId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.biaoshi
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private Integer biaoshi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.body_part
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private String bodyPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.count
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.unit
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private Integer unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.print
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private Integer print;

    private boolean deepSection;

    private Integer specialDye;

    private Long applyId;

    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.status
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.create_by
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.update_by
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.create_time
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.update_time
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.note
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private String note;

    private Long parentId;

    private String marker;

    private Boolean embedPause;

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public Integer getPrint() {
        return print;
    }

    public void setPrint(Integer print) {
        this.print = print;
    }

    public Boolean getEmbedPause() {
        return embedPause;
    }

    public void setEmbedPause(Boolean embedPause) {
        this.embedPause = embedPause;
    }

    public Long getApplyId() {
        return applyId;
    }

    public void setApplyId(Long applyId) {
        this.applyId = applyId;
    }

    public boolean isDeepSection() {
        return deepSection;
    }

    public void setDeepSection(boolean deepSection) {
        this.deepSection = deepSection;
    }

    public Integer getSpecialDye() {
        return specialDye;
    }

    public void setSpecialDye(Integer specialDye) {
        this.specialDye = specialDye;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public String getMarker() {
        return marker;
    }

    public void setMarker(String marker) {
        this.marker = marker;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table block
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.id
     *
     * @return the value of block.id
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.id
     *
     * @param id the value for block.id
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.serial_number
     *
     * @return the value of block.serial_number
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.serial_number
     *
     * @param serialNumber the value for block.serial_number
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.path_id
     *
     * @return the value of block.path_id
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public Long getPathId() {
        return pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.path_id
     *
     * @param pathId the value for block.path_id
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setPathId(Long pathId) {
        this.pathId = pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.sub_id
     *
     * @return the value of block.sub_id
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public String getSubId() {
        return subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.sub_id
     *
     * @param subId the value for block.sub_id
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setSubId(String subId) {
        this.subId = subId == null ? null : subId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.biaoshi
     *
     * @return the value of block.biaoshi
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public Integer getBiaoshi() {
        return biaoshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.biaoshi
     *
     * @param biaoshi the value for block.biaoshi
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setBiaoshi(Integer biaoshi) {
        this.biaoshi = biaoshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.body_part
     *
     * @return the value of block.body_part
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public String getBodyPart() {
        return bodyPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.body_part
     *
     * @param bodyPart the value for block.body_part
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setBodyPart(String bodyPart) {
        this.bodyPart = bodyPart == null ? null : bodyPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.count
     *
     * @return the value of block.count
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.count
     *
     * @param count the value for block.count
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.unit
     *
     * @return the value of block.unit
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.unit
     *
     * @param unit the value for block.unit
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.status
     *
     * @return the value of block.status
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.status
     *
     * @param status the value for block.status
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.create_by
     *
     * @return the value of block.create_by
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.create_by
     *
     * @param createBy the value for block.create_by
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.update_by
     *
     * @return the value of block.update_by
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.update_by
     *
     * @param updateBy the value for block.update_by
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.create_time
     *
     * @return the value of block.create_time
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.create_time
     *
     * @param createTime the value for block.create_time
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.update_time
     *
     * @return the value of block.update_time
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.update_time
     *
     * @param updateTime the value for block.update_time
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.note
     *
     * @return the value of block.note
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.note
     *
     * @param note the value for block.note
     *
     * @mbggenerated Tue Dec 06 11:49:26 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}