package com.lifetech.dhap.pathcloud.tracking.domain.model;

import java.io.Serializable;
import java.util.Date;

public class BlockScanImage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan_image.batch_id
     *
     * @mbggenerated Wed Mar 22 14:42:51 CST 2017
     */
    private Long batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan_image.image_path
     *
     * @mbggenerated Wed Mar 22 14:42:51 CST 2017
     */
    private String imagePath;

    private Integer imageSize;

    private String imageName;

    private String errorBlocks;

    private Integer scanLocation;

    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table block_scan_image
     *
     * @mbggenerated Wed Mar 22 14:42:51 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan_image.batch_id
     *
     * @return the value of block_scan_image.batch_id
     *
     * @mbggenerated Wed Mar 22 14:42:51 CST 2017
     */
    public Long getBatchId() {
        return batchId;
    }

    public Integer getScanLocation() {
        return scanLocation;
    }

    public void setScanLocation(Integer scanLocation) {
        this.scanLocation = scanLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan_image.batch_id
     *
     * @param batchId the value for block_scan_image.batch_id
     *
     * @mbggenerated Wed Mar 22 14:42:51 CST 2017
     */
    public void setBatchId(Long batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan_image.image_path
     *
     * @return the value of block_scan_image.image_path
     *
     * @mbggenerated Wed Mar 22 14:42:51 CST 2017
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan_image.image_path
     *
     * @param imagePath the value for block_scan_image.image_path
     *
     * @mbggenerated Wed Mar 22 14:42:51 CST 2017
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan_image.create_time
     *
     * @return the value of block_scan_image.create_time
     *
     * @mbggenerated Wed Mar 22 14:42:51 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan_image.create_time
     *
     * @param createTime the value for block_scan_image.create_time
     *
     * @mbggenerated Wed Mar 22 14:42:51 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Integer getImageSize() {
        return imageSize;
    }

    public void setImageSize(Integer imageSize) {
        this.imageSize = imageSize;
    }

    public String getImageName() {
        return imageName;
    }

    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    public String getErrorBlocks() {
        return errorBlocks;
    }

    public void setErrorBlocks(String errorBlocks) {
        this.errorBlocks = errorBlocks;
    }
}