package com.lifetech.dhap.pathcloud.tracking.domain.model;

import java.io.Serializable;
import java.util.Date;

public class BlockScan implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan.batch_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    private Long batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan.path_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    private Long pathId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan.block_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    private Long blockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan.slide_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    private Long slideId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan.path_no
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    private String pathNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan.patient_name
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan.block_sub_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    private String blockSubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan.biaoshi
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    private Integer biaoshi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan.marker
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    private String marker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan.special_dye
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    private Integer specialDye;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan.sub_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    private String subId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_scan.create_time
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table block_scan
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan.batch_id
     *
     * @return the value of block_scan.batch_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public Long getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan.batch_id
     *
     * @param batchId the value for block_scan.batch_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public void setBatchId(Long batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan.path_id
     *
     * @return the value of block_scan.path_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public Long getPathId() {
        return pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan.path_id
     *
     * @param pathId the value for block_scan.path_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public void setPathId(Long pathId) {
        this.pathId = pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan.block_id
     *
     * @return the value of block_scan.block_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public Long getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan.block_id
     *
     * @param blockId the value for block_scan.block_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public void setBlockId(Long blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan.slide_id
     *
     * @return the value of block_scan.slide_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public Long getSlideId() {
        return slideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan.slide_id
     *
     * @param slideId the value for block_scan.slide_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public void setSlideId(Long slideId) {
        this.slideId = slideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan.path_no
     *
     * @return the value of block_scan.path_no
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public String getPathNo() {
        return pathNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan.path_no
     *
     * @param pathNo the value for block_scan.path_no
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public void setPathNo(String pathNo) {
        this.pathNo = pathNo == null ? null : pathNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan.patient_name
     *
     * @return the value of block_scan.patient_name
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan.patient_name
     *
     * @param patientName the value for block_scan.patient_name
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan.block_sub_id
     *
     * @return the value of block_scan.block_sub_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public String getBlockSubId() {
        return blockSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan.block_sub_id
     *
     * @param blockSubId the value for block_scan.block_sub_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public void setBlockSubId(String blockSubId) {
        this.blockSubId = blockSubId == null ? null : blockSubId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan.biaoshi
     *
     * @return the value of block_scan.biaoshi
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public Integer getBiaoshi() {
        return biaoshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan.biaoshi
     *
     * @param biaoshi the value for block_scan.biaoshi
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public void setBiaoshi(Integer biaoshi) {
        this.biaoshi = biaoshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan.marker
     *
     * @return the value of block_scan.marker
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public String getMarker() {
        return marker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan.marker
     *
     * @param marker the value for block_scan.marker
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public void setMarker(String marker) {
        this.marker = marker == null ? null : marker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan.special_dye
     *
     * @return the value of block_scan.special_dye
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public Integer getSpecialDye() {
        return specialDye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan.special_dye
     *
     * @param specialDye the value for block_scan.special_dye
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public void setSpecialDye(Integer specialDye) {
        this.specialDye = specialDye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan.sub_id
     *
     * @return the value of block_scan.sub_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public String getSubId() {
        return subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan.sub_id
     *
     * @param subId the value for block_scan.sub_id
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public void setSubId(String subId) {
        this.subId = subId == null ? null : subId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_scan.create_time
     *
     * @return the value of block_scan.create_time
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_scan.create_time
     *
     * @param createTime the value for block_scan.create_time
     *
     * @mbggenerated Wed Mar 22 14:42:29 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}