package com.lifetech.dhap.pathcloud.tracking.domain.model;

import java.io.Serializable;
import java.util.Date;

public class BlockArchive implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.serial_number
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.path_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private Long pathId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.block_sub_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private String blockSubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.block_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private Long blockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.slide_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private Long slideId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.slide_sub_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private String slideSubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.status
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.ihc_marker
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private String ihcMarker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.patient_name
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.archive_box
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private String archiveBox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.archive_index
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private String archiveIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.create_by
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.update_by
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.create_time
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_archive.update_time
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table block_archive
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.id
     *
     * @return the value of block_archive.id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.id
     *
     * @param id the value for block_archive.id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.serial_number
     *
     * @return the value of block_archive.serial_number
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.serial_number
     *
     * @param serialNumber the value for block_archive.serial_number
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.path_id
     *
     * @return the value of block_archive.path_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public Long getPathId() {
        return pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.path_id
     *
     * @param pathId the value for block_archive.path_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setPathId(Long pathId) {
        this.pathId = pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.block_sub_id
     *
     * @return the value of block_archive.block_sub_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public String getBlockSubId() {
        return blockSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.block_sub_id
     *
     * @param blockSubId the value for block_archive.block_sub_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setBlockSubId(String blockSubId) {
        this.blockSubId = blockSubId == null ? null : blockSubId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.block_id
     *
     * @return the value of block_archive.block_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public Long getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.block_id
     *
     * @param blockId the value for block_archive.block_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setBlockId(Long blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.slide_id
     *
     * @return the value of block_archive.slide_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public Long getSlideId() {
        return slideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.slide_id
     *
     * @param slideId the value for block_archive.slide_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setSlideId(Long slideId) {
        this.slideId = slideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.slide_sub_id
     *
     * @return the value of block_archive.slide_sub_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public String getSlideSubId() {
        return slideSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.slide_sub_id
     *
     * @param slideSubId the value for block_archive.slide_sub_id
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setSlideSubId(String slideSubId) {
        this.slideSubId = slideSubId == null ? null : slideSubId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.status
     *
     * @return the value of block_archive.status
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.status
     *
     * @param status the value for block_archive.status
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.ihc_marker
     *
     * @return the value of block_archive.ihc_marker
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public String getIhcMarker() {
        return ihcMarker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.ihc_marker
     *
     * @param ihcMarker the value for block_archive.ihc_marker
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setIhcMarker(String ihcMarker) {
        this.ihcMarker = ihcMarker == null ? null : ihcMarker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.patient_name
     *
     * @return the value of block_archive.patient_name
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.patient_name
     *
     * @param patientName the value for block_archive.patient_name
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.archive_box
     *
     * @return the value of block_archive.archive_box
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public String getArchiveBox() {
        return archiveBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.archive_box
     *
     * @param archiveBox the value for block_archive.archive_box
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setArchiveBox(String archiveBox) {
        this.archiveBox = archiveBox == null ? null : archiveBox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.archive_index
     *
     * @return the value of block_archive.archive_index
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public String getArchiveIndex() {
        return archiveIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.archive_index
     *
     * @param archiveIndex the value for block_archive.archive_index
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setArchiveIndex(String archiveIndex) {
        this.archiveIndex = archiveIndex == null ? null : archiveIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.create_by
     *
     * @return the value of block_archive.create_by
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.create_by
     *
     * @param createBy the value for block_archive.create_by
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.update_by
     *
     * @return the value of block_archive.update_by
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.update_by
     *
     * @param updateBy the value for block_archive.update_by
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.create_time
     *
     * @return the value of block_archive.create_time
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.create_time
     *
     * @param createTime the value for block_archive.create_time
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_archive.update_time
     *
     * @return the value of block_archive.update_time
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_archive.update_time
     *
     * @param updateTime the value for block_archive.update_time
     *
     * @mbggenerated Wed Jun 07 15:18:21 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}