package com.lifetech.dhap.pathcloud.tracking.domain.model;

import java.io.Serializable;
import java.util.Date;

public class BlockBorrow implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.id
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.archive_id
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private Long archiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.borrow_name
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private String borrowName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.borrow_phone
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private String borrowPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.plan_back
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private Date planBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.real_back
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private Date realBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.borrow_type
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private Integer borrowType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.tutor
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private String tutor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.unit
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.note
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.departments
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private Integer departments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.status
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.archive_status
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private Integer archiveStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.create_by
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.update_by
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.create_time
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_borrow.update_time
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private Date updateTime;

    private String idNumber;

    private String cashPledge;

    public String getIdNumber() {
        return idNumber;
    }

    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    public String getCashPledge() {
        return cashPledge;
    }

    public void setCashPledge(String cashPledge) {
        this.cashPledge = cashPledge;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table block_borrow
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.id
     *
     * @return the value of block_borrow.id
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.id
     *
     * @param id the value for block_borrow.id
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.archive_id
     *
     * @return the value of block_borrow.archive_id
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public Long getArchiveId() {
        return archiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.archive_id
     *
     * @param archiveId the value for block_borrow.archive_id
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setArchiveId(Long archiveId) {
        this.archiveId = archiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.borrow_name
     *
     * @return the value of block_borrow.borrow_name
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public String getBorrowName() {
        return borrowName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.borrow_name
     *
     * @param borrowName the value for block_borrow.borrow_name
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setBorrowName(String borrowName) {
        this.borrowName = borrowName == null ? null : borrowName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.borrow_phone
     *
     * @return the value of block_borrow.borrow_phone
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public String getBorrowPhone() {
        return borrowPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.borrow_phone
     *
     * @param borrowPhone the value for block_borrow.borrow_phone
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setBorrowPhone(String borrowPhone) {
        this.borrowPhone = borrowPhone == null ? null : borrowPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.plan_back
     *
     * @return the value of block_borrow.plan_back
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public Date getPlanBack() {
        return planBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.plan_back
     *
     * @param planBack the value for block_borrow.plan_back
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setPlanBack(Date planBack) {
        this.planBack = planBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.real_back
     *
     * @return the value of block_borrow.real_back
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public Date getRealBack() {
        return realBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.real_back
     *
     * @param realBack the value for block_borrow.real_back
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setRealBack(Date realBack) {
        this.realBack = realBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.borrow_type
     *
     * @return the value of block_borrow.borrow_type
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public Integer getBorrowType() {
        return borrowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.borrow_type
     *
     * @param borrowType the value for block_borrow.borrow_type
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setBorrowType(Integer borrowType) {
        this.borrowType = borrowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.tutor
     *
     * @return the value of block_borrow.tutor
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public String getTutor() {
        return tutor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.tutor
     *
     * @param tutor the value for block_borrow.tutor
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setTutor(String tutor) {
        this.tutor = tutor == null ? null : tutor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.unit
     *
     * @return the value of block_borrow.unit
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.unit
     *
     * @param unit the value for block_borrow.unit
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.note
     *
     * @return the value of block_borrow.note
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.note
     *
     * @param note the value for block_borrow.note
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.departments
     *
     * @return the value of block_borrow.departments
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public Integer getDepartments() {
        return departments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.departments
     *
     * @param departments the value for block_borrow.departments
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setDepartments(Integer departments) {
        this.departments = departments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.status
     *
     * @return the value of block_borrow.status
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.status
     *
     * @param status the value for block_borrow.status
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.archive_status
     *
     * @return the value of block_borrow.archive_status
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public Integer getArchiveStatus() {
        return archiveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.archive_status
     *
     * @param archiveStatus the value for block_borrow.archive_status
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setArchiveStatus(Integer archiveStatus) {
        this.archiveStatus = archiveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.create_by
     *
     * @return the value of block_borrow.create_by
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.create_by
     *
     * @param createBy the value for block_borrow.create_by
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.update_by
     *
     * @return the value of block_borrow.update_by
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.update_by
     *
     * @param updateBy the value for block_borrow.update_by
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.create_time
     *
     * @return the value of block_borrow.create_time
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.create_time
     *
     * @param createTime the value for block_borrow.create_time
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_borrow.update_time
     *
     * @return the value of block_borrow.update_time
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_borrow.update_time
     *
     * @param updateTime the value for block_borrow.update_time
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}