package com.lifetech.dhap.pathcloud.tracking.domain.model;

import java.io.Serializable;
import java.util.Date;

public class PathTracking implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_tracking.id
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_tracking.path_id
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    private Long pathId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_tracking.operation
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    private Integer operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_tracking.operator_id
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_tracking.sec_operator_id
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    private Long secOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_tracking.operation_time
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    private Date operationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_tracking.note_type
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    private String noteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_tracking.create_by
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_tracking.update_by
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_tracking.create_time
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_tracking.update_time
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_tracking.note
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table path_tracking
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_tracking.id
     *
     * @return the value of path_tracking.id
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_tracking.id
     *
     * @param id the value for path_tracking.id
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_tracking.path_id
     *
     * @return the value of path_tracking.path_id
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public Long getPathId() {
        return pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_tracking.path_id
     *
     * @param pathId the value for path_tracking.path_id
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public void setPathId(Long pathId) {
        this.pathId = pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_tracking.operation
     *
     * @return the value of path_tracking.operation
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public Integer getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_tracking.operation
     *
     * @param operation the value for path_tracking.operation
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public void setOperation(Integer operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_tracking.operator_id
     *
     * @return the value of path_tracking.operator_id
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_tracking.operator_id
     *
     * @param operatorId the value for path_tracking.operator_id
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_tracking.sec_operator_id
     *
     * @return the value of path_tracking.sec_operator_id
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public Long getSecOperatorId() {
        return secOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_tracking.sec_operator_id
     *
     * @param secOperatorId the value for path_tracking.sec_operator_id
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public void setSecOperatorId(Long secOperatorId) {
        this.secOperatorId = secOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_tracking.operation_time
     *
     * @return the value of path_tracking.operation_time
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_tracking.operation_time
     *
     * @param operationTime the value for path_tracking.operation_time
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_tracking.note_type
     *
     * @return the value of path_tracking.note_type
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public String getNoteType() {
        return noteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_tracking.note_type
     *
     * @param noteType the value for path_tracking.note_type
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public void setNoteType(String noteType) {
        this.noteType = noteType == null ? null : noteType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_tracking.create_by
     *
     * @return the value of path_tracking.create_by
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_tracking.create_by
     *
     * @param createBy the value for path_tracking.create_by
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_tracking.update_by
     *
     * @return the value of path_tracking.update_by
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_tracking.update_by
     *
     * @param updateBy the value for path_tracking.update_by
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_tracking.create_time
     *
     * @return the value of path_tracking.create_time
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_tracking.create_time
     *
     * @param createTime the value for path_tracking.create_time
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_tracking.update_time
     *
     * @return the value of path_tracking.update_time
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_tracking.update_time
     *
     * @param updateTime the value for path_tracking.update_time
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_tracking.note
     *
     * @return the value of path_tracking.note
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_tracking.note
     *
     * @param note the value for path_tracking.note
     *
     * @mbggenerated Mon Jan 16 12:57:50 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}