package com.lifetech.dhap.pathcloud.tracking.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Tracking implements Serializable {

    private String marker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracking.id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracking.block_id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private Long blockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracking.operation
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private Integer operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracking.operator_id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private Long operatorId;

    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracking.sec_operator_id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private Long secOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracking.operation_time
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private Date operationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracking.manual_flag
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private Boolean manualFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracking.instrument_id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private Long instrumentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracking.create_by
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracking.update_by
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracking.create_time
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracking.update_time
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracking.note
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private String note;
    private String noteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tracking
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    private static final long serialVersionUID = 1L;

    public String getOperatorName() {
        return operatorName;
    }

    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    public String getNoteType() {
        return noteType;
    }

    public void setNoteType(String noteType) {
        this.noteType = noteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracking.id
     *
     * @return the value of tracking.id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */



    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracking.id
     *
     * @param id the value for tracking.id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracking.block_id
     *
     * @return the value of tracking.block_id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public Long getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracking.block_id
     *
     * @param blockId the value for tracking.block_id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public void setBlockId(Long blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracking.operation
     *
     * @return the value of tracking.operation
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public Integer getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracking.operation
     *
     * @param operation the value for tracking.operation
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public void setOperation(Integer operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracking.operator_id
     *
     * @return the value of tracking.operator_id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracking.operator_id
     *
     * @param operatorId the value for tracking.operator_id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracking.sec_operator_id
     *
     * @return the value of tracking.sec_operator_id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public Long getSecOperatorId() {
        return secOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracking.sec_operator_id
     *
     * @param secOperatorId the value for tracking.sec_operator_id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public void setSecOperatorId(Long secOperatorId) {
        this.secOperatorId = secOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracking.operation_time
     *
     * @return the value of tracking.operation_time
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracking.operation_time
     *
     * @param operationTime the value for tracking.operation_time
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracking.manual_flag
     *
     * @return the value of tracking.manual_flag
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public Boolean getManualFlag() {
        return manualFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracking.manual_flag
     *
     * @param manualFlag the value for tracking.manual_flag
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public void setManualFlag(Boolean manualFlag) {
        this.manualFlag = manualFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracking.instrument_id
     *
     * @return the value of tracking.instrument_id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public Long getInstrumentId() {
        return instrumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracking.instrument_id
     *
     * @param instrumentId the value for tracking.instrument_id
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public void setInstrumentId(Long instrumentId) {
        this.instrumentId = instrumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracking.create_by
     *
     * @return the value of tracking.create_by
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracking.create_by
     *
     * @param createBy the value for tracking.create_by
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracking.update_by
     *
     * @return the value of tracking.update_by
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracking.update_by
     *
     * @param updateBy the value for tracking.update_by
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracking.create_time
     *
     * @return the value of tracking.create_time
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracking.create_time
     *
     * @param createTime the value for tracking.create_time
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracking.update_time
     *
     * @return the value of tracking.update_time
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracking.update_time
     *
     * @param updateTime the value for tracking.update_time
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracking.note
     *
     * @return the value of tracking.note
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracking.note
     *
     * @param note the value for tracking.note
     *
     * @mbggenerated Wed Dec 07 13:36:11 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    public String getMarker() {
        return marker;
    }

    public void setMarker(String marker) {
        this.marker = marker;
    }
}