package com.lifetech.dhap.pathcloud.file.domain;

import com.lifetech.dhap.pathcloud.file.domain.model.PathologyFile;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PathologyFileRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pathology_file
     *
     * @mbggenerated Thu Dec 22 15:07:21 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pathology_file
     *
     * @mbggenerated Thu Dec 22 15:07:21 CST 2016
     */
    int insert(PathologyFile record);

    int batchInsert(List<PathologyFile> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pathology_file
     *
     * @mbggenerated Thu Dec 22 15:07:21 CST 2016
     */
    PathologyFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pathology_file
     *
     * @mbggenerated Thu Dec 22 15:07:21 CST 2016
     */
    List<PathologyFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pathology_file
     *
     * @mbggenerated Thu Dec 22 15:07:21 CST 2016
     */
    int updateByPrimaryKey(PathologyFile record);

    int batchUpdate(List<PathologyFile> records);

    List<PathologyFile> selectFileByPathologyId(@Param("pathologyId") Long pathologyId, @Param("operation") Integer operation,@Param("tag") String tag);

    PathologyFile selectFileByBlockId(Long blockId);

    PathologyFile selectFileBySavename(String savename);

    Long last();

    List<PathologyFile> selectConfirmFileByBlockIds(List<Long> list);
}