package com.lifetech.dhap.pathcloud.setting.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Template implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.id
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.name
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.category
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.parent
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    private Integer parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.level
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.position
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.display_order
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    private Integer displayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.create_by
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.update_by
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.create_time
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.update_time
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.content
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table template
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.id
     *
     * @return the value of template.id
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.id
     *
     * @param id the value for template.id
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.name
     *
     * @return the value of template.name
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.name
     *
     * @param name the value for template.name
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.category
     *
     * @return the value of template.category
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.category
     *
     * @param category the value for template.category
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.parent
     *
     * @return the value of template.parent
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.parent
     *
     * @param parent the value for template.parent
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.level
     *
     * @return the value of template.level
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.level
     *
     * @param level the value for template.level
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.position
     *
     * @return the value of template.position
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.position
     *
     * @param position the value for template.position
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.display_order
     *
     * @return the value of template.display_order
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.display_order
     *
     * @param displayOrder the value for template.display_order
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.create_by
     *
     * @return the value of template.create_by
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.create_by
     *
     * @param createBy the value for template.create_by
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.update_by
     *
     * @return the value of template.update_by
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.update_by
     *
     * @param updateBy the value for template.update_by
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.create_time
     *
     * @return the value of template.create_time
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.create_time
     *
     * @param createTime the value for template.create_time
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.update_time
     *
     * @return the value of template.update_time
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.update_time
     *
     * @param updateTime the value for template.update_time
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.content
     *
     * @return the value of template.content
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.content
     *
     * @param content the value for template.content
     *
     * @mbggenerated Wed Dec 07 13:28:36 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}