package com.lifetech.dhap.pathcloud.notification.dto;

import java.io.Serializable;
import java.util.Date;

public class NotificationReceiverDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification_receiver.notification_id
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    private Long notificationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification_receiver.receiver_id
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    private Long receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification_receiver.read_flag
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    private Boolean readFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification_receiver.read_time
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    private Date readTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_notification_receiver
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification_receiver.notification_id
     *
     * @return the value of system_notification_receiver.notification_id
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    public Long getNotificationId() {
        return notificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification_receiver.notification_id
     *
     * @param notificationId the value for system_notification_receiver.notification_id
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    public void setNotificationId(Long notificationId) {
        this.notificationId = notificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification_receiver.receiver_id
     *
     * @return the value of system_notification_receiver.receiver_id
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    public Long getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification_receiver.receiver_id
     *
     * @param receiverId the value for system_notification_receiver.receiver_id
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification_receiver.read_flag
     *
     * @return the value of system_notification_receiver.read_flag
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    public Boolean getReadFlag() {
        return readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification_receiver.read_flag
     *
     * @param readFlag the value for system_notification_receiver.read_flag
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    public void setReadFlag(Boolean readFlag) {
        this.readFlag = readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification_receiver.read_time
     *
     * @return the value of system_notification_receiver.read_time
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification_receiver.read_time
     *
     * @param readTime the value for system_notification_receiver.read_time
     *
     * @mbggenerated Mon Feb 13 13:30:44 CST 2017
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }
}