package com.lifetech.dhap.pathcloud.user.domain;

import com.lifetech.dhap.pathcloud.user.domain.model.Permission;
import java.util.List;

public interface PermissionRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Tue Nov 08 12:38:37 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Tue Nov 08 12:38:37 CST 2016
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Tue Nov 08 12:38:37 CST 2016
     */
    Permission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Tue Nov 08 12:38:37 CST 2016
     */
    List<Permission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Tue Nov 08 12:38:37 CST 2016
     */
    int updateByPrimaryKey(Permission record);

    List<Permission> selectByRoleId(Long roleId);

    Permission selectByCode(Integer code);
}