package com.lifetech.dhap.pathcloud.user.domain;

import com.lifetech.dhap.pathcloud.user.application.condition.RoleCondition;
import com.lifetech.dhap.pathcloud.user.domain.model.Role;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoleRepository {

    List<Role> selectByCondition(RoleCondition condition);

    Long countByCondition(RoleCondition con);

    Role selectByName(String name);

    int insertMapping(@Param("roleId") Long roleId,@Param("permissionId") Integer permissionId);

    int deleteMapping(@Param("roleId")Long roleId,@Param("permissionId") Integer permissionId);

    Long last();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Nov 08 12:37:49 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Nov 08 12:37:49 CST 2016
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Nov 08 12:37:49 CST 2016
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Nov 08 12:37:49 CST 2016
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Nov 08 12:37:49 CST 2016
     */
    int updateByPrimaryKey(Role record);
}