package com.lifetech.dhap.pathcloud.user.domain;

import com.lifetech.dhap.pathcloud.user.application.condition.UserCondition;
import com.lifetech.dhap.pathcloud.user.domain.model.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserRepository {

    /**
     * This method was generated by MyBatis Generator.
* This method corresponds to the database table user
     *
     * @mbggenerated Fri Apr 15 14:50:55 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Apr 15 14:50:55 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Apr 15 14:50:55 CST 2016
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Apr 15 14:50:55 CST 2016
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Apr 15 14:50:55 CST 2016
     */
    int updateByPrimaryKey(User record);

    User selectByUsername(String userName);

    List<User> selectByCondition(UserCondition con);

    Long countByCondition(UserCondition con);

    Long last();

    int updateLoginInfo(@Param("id") Long id, @Param("ip") String ip);

    int resetPassword(@Param("id") Long id, @Param("password") String password, @Param("qrCode") String qrCode);

    /**
     * 获取用户权限
     * @param userId
     * @return
     */
    List<Integer> selectUserPermissionsCode(@Param("userId") Long userId);

    List<Long> selectSentReport();

    List<Long> selectIdByFirstName(String firstName);
}
