package com.lifetech.dhap.pathcloud.dehydrate.domain.model;

import java.io.Serializable;
import java.util.Date;

public class InstrumentEventCode implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument_event_code.id
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument_event_code.instrument_id
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    private Long instrumentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument_event_code.code
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument_event_code.msg
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument_event_code.level
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument_event_code.create_by
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument_event_code.update_by
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument_event_code.create_time
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument_event_code.update_time
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table instrument_event_code
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument_event_code.id
     *
     * @return the value of instrument_event_code.id
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument_event_code.id
     *
     * @param id the value for instrument_event_code.id
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument_event_code.instrument_id
     *
     * @return the value of instrument_event_code.instrument_id
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public Long getInstrumentId() {
        return instrumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument_event_code.instrument_id
     *
     * @param instrumentId the value for instrument_event_code.instrument_id
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public void setInstrumentId(Long instrumentId) {
        this.instrumentId = instrumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument_event_code.code
     *
     * @return the value of instrument_event_code.code
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument_event_code.code
     *
     * @param code the value for instrument_event_code.code
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument_event_code.msg
     *
     * @return the value of instrument_event_code.msg
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument_event_code.msg
     *
     * @param msg the value for instrument_event_code.msg
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument_event_code.level
     *
     * @return the value of instrument_event_code.level
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument_event_code.level
     *
     * @param level the value for instrument_event_code.level
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument_event_code.create_by
     *
     * @return the value of instrument_event_code.create_by
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument_event_code.create_by
     *
     * @param createBy the value for instrument_event_code.create_by
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument_event_code.update_by
     *
     * @return the value of instrument_event_code.update_by
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument_event_code.update_by
     *
     * @param updateBy the value for instrument_event_code.update_by
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument_event_code.create_time
     *
     * @return the value of instrument_event_code.create_time
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument_event_code.create_time
     *
     * @param createTime the value for instrument_event_code.create_time
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument_event_code.update_time
     *
     * @return the value of instrument_event_code.update_time
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument_event_code.update_time
     *
     * @param updateTime the value for instrument_event_code.update_time
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}