package com.lifetech.dhap.pathcloud.dehydrate.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Instrument implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument.id
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument.type
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument.name
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument.sn
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    private String sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument.in_use
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    private Boolean inUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument.last_heartbreak
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    private Long lastHeartbreak;

    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument.disabled
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument.create_by
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument.update_by
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument.create_time
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument.update_time
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instrument.description
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    private String description;

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table instrument
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument.id
     *
     * @return the value of instrument.id
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument.id
     *
     * @param id the value for instrument.id
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument.type
     *
     * @return the value of instrument.type
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument.type
     *
     * @param type the value for instrument.type
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument.name
     *
     * @return the value of instrument.name
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument.name
     *
     * @param name the value for instrument.name
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument.sn
     *
     * @return the value of instrument.sn
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument.sn
     *
     * @param sn the value for instrument.sn
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument.in_use
     *
     * @return the value of instrument.in_use
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public Boolean getInUse() {
        return inUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument.in_use
     *
     * @param inUse the value for instrument.in_use
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public void setInUse(Boolean inUse) {
        this.inUse = inUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument.last_heartbreak
     *
     * @return the value of instrument.last_heartbreak
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public Long getLastHeartbreak() {
        return lastHeartbreak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument.last_heartbreak
     *
     * @param lastHeartbreak the value for instrument.last_heartbreak
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public void setLastHeartbreak(Long lastHeartbreak) {
        this.lastHeartbreak = lastHeartbreak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument.disabled
     *
     * @return the value of instrument.disabled
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument.disabled
     *
     * @param disabled the value for instrument.disabled
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument.create_by
     *
     * @return the value of instrument.create_by
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument.create_by
     *
     * @param createBy the value for instrument.create_by
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument.update_by
     *
     * @return the value of instrument.update_by
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument.update_by
     *
     * @param updateBy the value for instrument.update_by
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument.create_time
     *
     * @return the value of instrument.create_time
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument.create_time
     *
     * @param createTime the value for instrument.create_time
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument.update_time
     *
     * @return the value of instrument.update_time
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument.update_time
     *
     * @param updateTime the value for instrument.update_time
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instrument.description
     *
     * @return the value of instrument.description
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instrument.description
     *
     * @param description the value for instrument.description
     *
     * @mbggenerated Wed Dec 14 14:18:02 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}