package com.lifetech.dhap.pathcloud.dehydrate.domain;

import com.lifetech.dhap.pathcloud.dehydrate.domain.model.InstrumentEventCode;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface InstrumentEventCodeRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instrument_event_code
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instrument_event_code
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    int insert(InstrumentEventCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instrument_event_code
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    InstrumentEventCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instrument_event_code
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    List<InstrumentEventCode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instrument_event_code
     *
     * @mbggenerated Mon Dec 12 17:28:08 CST 2016
     */
    int updateByPrimaryKey(InstrumentEventCode record);
    
    InstrumentEventCode selectByCode(@Param("instrumentId") long instrumentId, @Param("code") String code);
}