package com.lifetech.dhap.pathcloud.tracking.domain;

import com.lifetech.dhap.pathcloud.tracking.application.condition.ArchiveCondition;
import com.lifetech.dhap.pathcloud.tracking.application.dto.BrrowHistoryDto;
import com.lifetech.dhap.pathcloud.tracking.application.dto.SlideArchiveInfoDto;
import com.lifetech.dhap.pathcloud.tracking.domain.model.BlockBorrow;
import java.util.List;

public interface BlockBorrowRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_borrow
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_borrow
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    int insert(BlockBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_borrow
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    BlockBorrow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_borrow
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    List<BlockBorrow> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_borrow
     *
     * @mbggenerated Thu Jun 08 10:39:21 CST 2017
     */
    int updateByPrimaryKey(BlockBorrow record);

    List<SlideArchiveInfoDto> selectSlidesBorrowInfo(ArchiveCondition con);

    List<SlideArchiveInfoDto> selectOverdueBorrowInfo();

    SlideArchiveInfoDto selectBlockBorrowDetail(Long borrowId);

    List<BrrowHistoryDto> getSlidesBrrowHistory(Long blockArchiveId);
}