package com.lifetech.dhap.pathcloud.tracking.domain;

import com.lifetech.dhap.pathcloud.tracking.application.condition.CollectCondition;
import com.lifetech.dhap.pathcloud.tracking.application.dto.CollectDetailDto;
import com.lifetech.dhap.pathcloud.tracking.application.dto.CollectDto;
import com.lifetech.dhap.pathcloud.tracking.domain.model.Collect;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Wed Sep 27 14:59:55 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Wed Sep 27 14:59:55 CST 2017
     */
    int insert(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Wed Sep 27 14:59:55 CST 2017
     */
    Collect selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Wed Sep 27 14:59:55 CST 2017
     */
    List<Collect> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Wed Sep 27 14:59:55 CST 2017
     */
    int updateByPrimaryKey(Collect record);

    Long getCollectsTotal(CollectCondition con);

    List<CollectDetailDto> getCollects(CollectCondition con);

    Collect selectCollectByCondition(CollectCondition collectCondition);

    Collect getCollectByIdAndCreateBy(@Param("id") Long id,@Param("createById") Long createById);
}