package com.lifetech.dhap.pathcloud.tracking.domain;

import com.lifetech.dhap.pathcloud.tracking.application.condition.MicroscopeTrackingCon;
import com.lifetech.dhap.pathcloud.tracking.application.dto.MicroscopeTrackingDto;
import com.lifetech.dhap.pathcloud.tracking.domain.model.MicroscopeTracking;

import java.util.List;

public interface MicroscopeTrackingRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microscope_tracking
     *
     * @mbggenerated Thu Jun 22 10:02:01 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microscope_tracking
     *
     * @mbggenerated Thu Jun 22 10:02:01 CST 2017
     */
    int insert(MicroscopeTracking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microscope_tracking
     *
     * @mbggenerated Thu Jun 22 10:02:01 CST 2017
     */
    MicroscopeTracking selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microscope_tracking
     *
     * @mbggenerated Thu Jun 22 10:02:01 CST 2017
     */
    List<MicroscopeTracking> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microscope_tracking
     *
     * @mbggenerated Thu Jun 22 10:02:01 CST 2017
     */
    int updateByPrimaryKey(MicroscopeTracking record);

    MicroscopeTracking selectUserMicroscopeTracking(Long bookingPid);

    List<MicroscopeTrackingDto> selectByCondition(MicroscopeTrackingCon condition);

    Long countByCondition(MicroscopeTrackingCon condition);
}