package com.lifetech.dhap.pathcloud.tracking.domain;

import com.lifetech.dhap.pathcloud.tracking.application.condition.SpecialApplicationCondition;
import com.lifetech.dhap.pathcloud.tracking.domain.model.SpecialApplication;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SpecialApplicationRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_application
     *
     * @mbggenerated Mon Sep 25 15:51:40 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_application
     *
     * @mbggenerated Mon Sep 25 15:51:40 CST 2017
     */
    int insert(SpecialApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_application
     *
     * @mbggenerated Mon Sep 25 15:51:40 CST 2017
     */
    SpecialApplication selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_application
     *
     * @mbggenerated Mon Sep 25 15:51:40 CST 2017
     */
    List<SpecialApplication> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_application
     *
     * @mbggenerated Mon Sep 25 15:51:40 CST 2017
     */
    int updateByPrimaryKey(SpecialApplication record);

    SpecialApplication selectByNumber(String number);

    SpecialApplication selectByPathNoAndType(@Param("pathNo") String pathNo,@Param("type") Integer type);

    List<SpecialApplication> selectListByCondition(SpecialApplicationCondition condition);
    Long countByCondition(SpecialApplicationCondition condition);

    Integer selectSlideMinStatusByTrackingId(long trackingId);

    List<String> selectFrozenNumbersByPathNo(String pathNo);

    List<String> selectFrozenResultByPathNo(String pathNo);
}