package com.lifetech.dhap.pathcloud.notification.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Notification implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.id
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.subject
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.source
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.content
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.note
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.type
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private Integer type;

    private Long pathId;

    private Integer blockStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.block_id
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private Long blockId;


    private Integer abnormalHandle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.read_flag
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private Boolean readFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.receiver_type
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private Integer receiverType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.receiver_id
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private Long receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.create_by
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.update_by
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.create_time
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.update_time
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_notification
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.id
     *
     * @return the value of system_notification.id
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.id
     *
     * @param id the value for system_notification.id
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.subject
     *
     * @return the value of system_notification.subject
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.subject
     *
     * @param subject the value for system_notification.subject
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.source
     *
     * @return the value of system_notification.source
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.source
     *
     * @param source the value for system_notification.source
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.content
     *
     * @return the value of system_notification.content
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.content
     *
     * @param content the value for system_notification.content
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.note
     *
     * @return the value of system_notification.note
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.note
     *
     * @param note the value for system_notification.note
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.type
     *
     * @return the value of system_notification.type
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.type
     *
     * @param type the value for system_notification.type
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.block_id
     *
     * @return the value of system_notification.block_id
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public Long getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.block_id
     *
     * @param blockId the value for system_notification.block_id
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setBlockId(Long blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.read_flag
     *
     * @return the value of system_notification.read_flag
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public Boolean getReadFlag() {
        return readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.read_flag
     *
     * @param readFlag the value for system_notification.read_flag
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setReadFlag(Boolean readFlag) {
        this.readFlag = readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.receiver_type
     *
     * @return the value of system_notification.receiver_type
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public Integer getReceiverType() {
        return receiverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.receiver_type
     *
     * @param receiverType the value for system_notification.receiver_type
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setReceiverType(Integer receiverType) {
        this.receiverType = receiverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.receiver_id
     *
     * @return the value of system_notification.receiver_id
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public Long getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.receiver_id
     *
     * @param receiverId the value for system_notification.receiver_id
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.create_by
     *
     * @return the value of system_notification.create_by
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.create_by
     *
     * @param createBy the value for system_notification.create_by
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.update_by
     *
     * @return the value of system_notification.update_by
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.update_by
     *
     * @param updateBy the value for system_notification.update_by
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.create_time
     *
     * @return the value of system_notification.create_time
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.create_time
     *
     * @param createTime the value for system_notification.create_time
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.update_time
     *
     * @return the value of system_notification.update_time
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.update_time
     *
     * @param updateTime the value for system_notification.update_time
     *
     * @mbggenerated Thu Jan 05 12:03:38 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getAbnormalHandle() {
        return abnormalHandle;
    }

    public void setAbnormalHandle(Integer abnormalHandle) {
        this.abnormalHandle = abnormalHandle;
    }

    public Long getPathId() {
        return pathId;
    }

    public void setPathId(Long pathId) {
        this.pathId = pathId;
    }

    public Integer getBlockStatus() {
        return blockStatus;
    }

    public void setBlockStatus(Integer blockStatus) {
        this.blockStatus = blockStatus;
    }
}